### ISSUE TITLE
unused legend utility functions

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/TFL-Library#179]
As far as I can see, these functions are not used anywhere:
https://github.com/Open-Systems-Pharmacology/TLF-Library/blob/develop/R/utilities-legend.R

Also, I think some of them wouldn't even work if there were to be used somewhere. For example, there is no object called `newPlotObject` in this function:

https://github.com/Open-Systems-Pharmacology/TLF-Library/blob/be21543cd318e27f3aea679a6ae3d3ecd5252600/R/utilities-legend.R#L228

Should we remove these functions? Or should we move them to WIP folder or something?

**Comment by pchelle** [comment]
The "caption" object is a data.frame that I created to track the legend obtained from atom plots.
So we can know the `breaks`, `labels`, `visibility`, `color`, `fill`, `shape`, etc for each legend entry

**Comment by IndrajeetPatil** [comment]
Huh, I see. A bit non-idiomatic for R, but if it works, it works.
