### ISSUE TITLE
New shape scale is not very differentiating

### ISSUE THREAD

**Issue by Felixmil** [Open-Systems-Pharmacology/TFL-Library#429]
Since #395 I find the shape scale not very differentiating. For exemple:

```r
devtools::load_all(".")

obsVsPredData <- data.frame(x = c(1, 2, 1, 2, 3), y = c(5, 0.2, 2, 3, 4), group = c("A","A","B","B","B"))

plotConfiguration <- ObsVsPredPlotConfiguration$new(
    foldLinesLegend = TRUE,
    xScale = Scaling$log, xLimits = c(0.05, 50),
    yScale = Scaling$log, yLimits = c(0.05, 50)
  )

plotObsVsPred(
    data = obsVsPredData,
    dataMapping = ObsVsPredDataMapping$new(x = "x", y = "y", group="group"),
    plotConfiguration = plotConfiguration,
    foldDistance = 1
)
```

![image](https://user-images.githubusercontent.com/34234913/226700004-b8b4cf5b-9058-4956-9a0a-66cc86c40b4f.png)

**Having other filled shapes first instead of an alternance of filled/open shapes would yield better plots in my opinion.**

I think this is due to the new ordering of `Shapes` :
```r
> Shapes
$circle
[1] "⬤"

$circleOpen
[1] "🞅"

$diamond
[1] "⯁"

$diamondOpen
[1] "🝔"

$triangle
[1] "▲"

$triangleOpen
[1] "🜂"

$square
[1] "■"

$squareOpen
[1] "□"

...
```

**Comment by PavelBal** [comment]
Yes I fully agree. I am in favor of re-ordering.

**Comment by Yuri05** [comment]
>Since https://github.com/Open-Systems-Pharmacology/TLF-Library/issues/395 I find the shape scale not very differentiating. 

You mean, because datacombined takes the shapes in the order of their appearance in the shapes list?
@pchelle I think reordering (e.g. all filled shapes first then all open shapes etc.) should not be a problem (in terms of side effects)?

**Comment by Felixmil** [comment]
### Ordering of `Shapes`
The previous `Shapes` definition was this: https://github.com/Open-Systems-Pharmacology/TLF-Library/blob/bfa759a74f2ef726b13759f2a02f6daf1d38c724/R/utilities-enums.R#L297-L339
Now it is defined like this:
https://github.com/Open-Systems-Pharmacology/TLF-Library/blob/5b51e081c32fa1b31bc9117d192e94e5b0a6b9e3/R/utilities-enums.R#L360-L406

I think the default should be as the previous definition: plain shapes *then* open ones.
The only side effect I can see code-base wise is the refresh of all the snapshots.

### However, if a plain/open shapes alternance is needed somewhere

we can add a new function in `utilities-aesthetic.R` that would be called by `.getAestheticValues()` (same function family as .getNextAestheticValues`()`) and that would append "Open" to the preselected shapes names.

```r
newShapes <- list(circle = Shapes$circle, 
                  square=Shapes$square,
                  triangle=Shapes$triangle, 
                  circleOpen=Shapes$circleOpen, 
                  squareOpen=Shapes$squareOpen, 
                  triangleOpen=Shapes$triangleOpen)

.getAltPlainOpenShapes <- function(n, position = 0, map = newShapes) {
    # Half of the total are plain shape
    shapes <- map[seq(position, n/2)]

    # for each shape, we get its "Open" version
    for (name in names(shapes)) {
        alt <- paste0(name, "Open")
        shapes[alt] <- map[alt]
    }
    
    # Return names-sorted list to get a plain/open alternation
    return(shapes[order(names(shapes))])
}
```

For exemple for n=6:

```r
.getAltPlainOpenShapes(6)
```
```
$circle
[1] "⬤"

$circleOpen
[1] "🞅"

$square
[1] "■"

$squareOpen
[1] "□"

$triangle
[1] "▲"

$triangleOpen
[1] "🜂"
```

**Comment by Yuri05** [comment]
>However, if a plain/open shapes alternance is needed somewhere 

Right now, I don't see any use case where something like this would be required.
